---
- name: Add php repository
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: Installing php
  ansible.builtin.apt:
    name: "{{ php_packages_ubuntu }}"
    state: fixed

- name: Start service php-fpm, if not started
  ansible.builtin.service:
    name: php{{ php_version_ubuntu }}-fpm
    state: restarted
    enabled: true
