---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    ansible.builtin.assert:
      that: true
  - name: MySQL install
    ansible.builtin.package:
      name: mysqld
      state: present
  - name: MySQL start and enabled
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true
