---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-docker-centos-8
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    tmpfs:
      - /run
      - /tnp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
