---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    ansible.builtin.assert:
      that: true
  - name: PHP - installed
    ansible.builtin.package:
      name: php74-php-fpm
      state: present
  - name: PHP - start and enabled
    ansible.builtin.service:
      name: php74-php-fpm
      state: started
      enabled: true
